import type { ManagedAlgorithmProblemSeed } from "./algorithm-catalog";

type CompactSeed = Pick<
  ManagedAlgorithmProblemSeed,
  | "ref"
  | "title"
  | "difficultyBand"
  | "statementMarkdown"
  | "inputSpecification"
  | "outputSpecification"
  | "examples"
  | "skills"
  | "transferGroup"
> & {
  hints: readonly [string, string, string, string];
};

const DEFAULT_STARTER = {
  cpp17: [
    "#include <algorithm>",
    "#include <iostream>",
    "#include <string>",
    "#include <vector>",
    "using namespace std;",
    "",
    "int main() {",
    "    ios::sync_with_stdio(false);",
    "    cin.tie(nullptr);",
    "    // 读取输入并完成算法",
    "    return 0;",
    "}",
    "",
  ].join("\n"),
  python3: "# 读取输入并完成算法\n",
};

const HINT_TITLES = ["检查输入", "识别模型", "实现骨架", "参考方向"] as const;

function defineProblem(input: CompactSeed): ManagedAlgorithmProblemSeed {
  return {
    ...input,
    examples: [...input.examples],
    supportedLanguages: ["cpp17", "python3"],
    hints: input.hints.map((body, index) => ({
      level: (index + 1) as 1 | 2 | 3 | 4,
      title: HINT_TITLES[index],
      body,
    })),
    timeLimitMs: 1_000,
    memoryLimitKb: 131_072,
    starterCode: { ...DEFAULT_STARTER },
  };
}

export const EXPANDED_ALGORITHM_CATALOG: readonly ManagedAlgorithmProblemSeed[] = [
  defineProblem({
    ref: "ascend:foundation:parity-label:v1",
    title: "奇偶标签",
    difficultyBand: "foundation",
    statementMarkdown: "给定一个整数 $n$，若它是偶数输出 `EVEN`，否则输出 `ODD`。",
    inputSpecification: "一行一个整数 $n$，$|n|\\le10^{18}$。",
    outputSpecification: "输出 `EVEN` 或 `ODD`。",
    examples: [
      { input: "-3\n", output: "ODD\n" },
      { input: "8\n", output: "EVEN\n" },
    ],
    skills: ["input-output", "conditional", "parity", "boundary-negative"],
    transferGroup: "integer-classification",
    hints: [
      "负数也有奇偶性，语言的取模结果不影响判断余数是否为零。",
      "判断一个整数能否被 2 整除。",
      "读取 n；若 n % 2 == 0 输出 EVEN，否则输出 ODD。",
      "只需一次条件判断，使用 64 位整数。",
    ],
  }),
  defineProblem({
    ref: "ascend:foundation:max-three:v1",
    title: "三个数的最大值",
    difficultyBand: "foundation",
    statementMarkdown: "读取三个整数，输出其中的最大值。",
    inputSpecification: "一行包含三个整数，每个整数绝对值不超过 $10^{18}$。",
    outputSpecification: "输出一个整数，表示三者的最大值。",
    examples: [
      { input: "3 9 4\n", output: "9\n" },
      { input: "-5 -2 -7\n", output: "-2\n" },
    ],
    skills: ["conditional", "comparison", "boundary-negative"],
    transferGroup: "integer-classification",
    hints: [
      "全为负数时不能把初始最大值设成 0。",
      "从第一个数开始维护当前最大值。",
      "依次用第二、第三个数更新 maximum。",
      "可以使用两次比较，也可以使用语言提供的 max。",
    ],
  }),
  defineProblem({
    ref: "ascend:foundation:leap-year:v1",
    title: "闰年判定",
    difficultyBand: "foundation",
    statementMarkdown: "判断给定公历年份是否为闰年：能被 400 整除，或能被 4 整除但不能被 100 整除。",
    inputSpecification: "一行一个年份 $y$，$1\\le y\\le9999$。",
    outputSpecification: "闰年输出 `YES`，否则输出 `NO`。",
    examples: [
      { input: "2000\n", output: "YES\n" },
      { input: "1900\n", output: "NO\n" },
    ],
    skills: ["conditional", "boolean-logic", "divisibility"],
    transferGroup: "integer-classification",
    hints: [
      "世纪年需要单独处理，1900 和 2000 的结果不同。",
      "把规则写成两个条件用“或”连接。",
      "(y % 400 == 0) 或 (y % 4 == 0 且 y % 100 != 0)。",
      "先写布尔表达式，再根据真假输出固定字符串。",
    ],
  }),
  defineProblem({
    ref: "ascend:foundation:digit-sum:v1",
    title: "各位数字之和",
    difficultyBand: "foundation",
    statementMarkdown: "给定一个整数 $n$，求其十进制表示中各位数字之和，负号不计。",
    inputSpecification: "一行一个整数 $n$，$|n|\\le10^{18}$。",
    outputSpecification: "输出非负整数，表示各位数字之和。",
    examples: [
      { input: "50203\n", output: "10\n" },
      { input: "-900\n", output: "9\n" },
    ],
    skills: ["loop", "integer-arithmetic", "digit-processing", "boundary-negative"],
    transferGroup: "digit-scan",
    hints: [
      "先消除负号；输入为 0 时答案仍是 0。",
      "反复取除以 10 的余数可得到最低位。",
      "令 n=abs(n)，循环累加 n%10，然后 n 整除 10。",
      "也可以把输入当字符串扫描，但应明确忽略负号。",
    ],
  }),
  defineProblem({
    ref: "ascend:foundation:count-positive:v1",
    title: "统计正数",
    difficultyBand: "foundation",
    statementMarkdown: "给定 $n$ 个整数，统计其中严格大于 0 的数有多少个。",
    inputSpecification: "第一行是 $n$；第二行是 $n$ 个整数，$1\\le n\\le2\\times10^5$。",
    outputSpecification: "输出正数的个数。",
    examples: [
      { input: "5\n-1 0 2 3 -4\n", output: "2\n" },
      { input: "1\n0\n", output: "0\n" },
    ],
    skills: ["array-scan", "counting", "comparison"],
    transferGroup: "linear-scan",
    hints: [
      "0 不是正数。",
      "扫描数组时维护一个计数器。",
      "每读到一个 x，若 x>0 就让计数器加一。",
      "无需保存整个数组，可以边读边统计。",
    ],
  }),
  defineProblem({
    ref: "ascend:foundation:array-minmax:v1",
    title: "数组最小值与最大值",
    difficultyBand: "foundation",
    statementMarkdown: "给定一个非空整数数组，输出最小值和最大值。",
    inputSpecification: "第一行是 $n$；第二行是 $n$ 个整数，$1\\le n\\le2\\times10^5$。",
    outputSpecification: "输出两个整数：最小值和最大值。",
    examples: [
      { input: "5\n3 -2 9 9 0\n", output: "-2 9\n" },
      { input: "1\n7\n", output: "7 7\n" },
    ],
    skills: ["array-scan", "minimum", "maximum", "invariant"],
    transferGroup: "linear-scan",
    hints: [
      "数组非空，因此可用第一个元素初始化两个答案。",
      "维护“已扫描前缀的最小值和最大值”不变式。",
      "对每个 x 分别更新 minValue 与 maxValue。",
      "不要用 0 初始化，否则全正或全负输入会出错。",
    ],
  }),
  defineProblem({
    ref: "ascend:foundation:reverse-array:v1",
    title: "反向输出数组",
    difficultyBand: "foundation",
    statementMarkdown: "给定一个数组，按相反顺序输出全部元素。",
    inputSpecification: "第一行是 $n$；第二行是 $n$ 个整数，$1\\le n\\le2\\times10^5$。",
    outputSpecification: "一行输出逆序后的 $n$ 个整数，空格分隔。",
    examples: [
      { input: "5\n1 2 3 4 5\n", output: "5 4 3 2 1\n" },
      { input: "1\n-7\n", output: "-7\n" },
    ],
    skills: ["array", "indexing", "reverse"],
    transferGroup: "array-transform",
    hints: [
      "只有一个元素时输出不变。",
      "可以从下标 n-1 遍历到 0。",
      "读取数组；倒序输出并控制空格。",
      "也可以原地交换首尾元素后正序输出。",
    ],
  }),
  defineProblem({
    ref: "ascend:foundation:second-largest:v1",
    title: "第二大不同值",
    difficultyBand: "foundation",
    statementMarkdown: "给定至少包含两个不同值的整数数组，输出第二大的不同值。",
    inputSpecification: "第一行是 $n$；第二行是 $n$ 个整数，$2\\le n\\le2\\times10^5$。",
    outputSpecification: "输出第二大的不同整数。",
    examples: [
      { input: "6\n4 1 4 3 2 3\n", output: "3\n" },
      { input: "3\n-5 -2 -3\n", output: "-3\n" },
    ],
    skills: ["array-scan", "top-two", "duplicates", "invariant"],
    transferGroup: "linear-scan",
    hints: [
      "重复出现的最大值不能成为第二大不同值。",
      "维护 largest 和 second，并跳过与 largest 相等的值。",
      "遇到更大值时把旧 largest 下放；否则尝试更新 second。",
      "也可去重排序，但线性扫描能做到 O(n) 时间和 O(1) 额外空间。",
    ],
  }),
  defineProblem({
    ref: "ascend:foundation:longest-increasing-run:v1",
    title: "最长连续递增段",
    difficultyBand: "foundation",
    statementMarkdown: "求数组中严格递增的最长连续子段长度。",
    inputSpecification: "第一行是 $n$；第二行是 $n$ 个整数，$1\\le n\\le2\\times10^5$。",
    outputSpecification: "输出最长连续递增子段的长度。",
    examples: [
      { input: "7\n1 2 3 2 3 4 5\n", output: "4\n" },
      { input: "5\n5 4 3 2 1\n", output: "1\n" },
    ],
    skills: ["array-scan", "contiguous-segment", "state-machine"],
    transferGroup: "linear-scan",
    hints: [
      "这里要求连续，不能跳过中间元素。",
      "比较当前元素与前一个元素，维护当前段长度。",
      "若 a[i]>a[i-1] 则 current++，否则 current=1，并更新答案。",
      "一次线性扫描即可，初始 current 和 answer 都是 1。",
    ],
  }),
  defineProblem({
    ref: "ascend:foundation:palindrome:v1",
    title: "回文字符串",
    difficultyBand: "foundation",
    statementMarkdown: "判断只含小写英文字母的字符串是否正读和反读完全相同。",
    inputSpecification: "一行一个非空字符串，长度不超过 $2\\times10^5$。",
    outputSpecification: "是回文串输出 `YES`，否则输出 `NO`。",
    examples: [
      { input: "level\n", output: "YES\n" },
      { input: "algorithm\n", output: "NO\n" },
    ],
    skills: ["string", "two-pointers", "symmetry"],
    transferGroup: "two-pointers",
    hints: [
      "需要比较首尾对称位置。",
      "使用 left 和 right 两个指针向中间移动。",
      "任一对字符不同就输出 NO；全部相同输出 YES。",
      "也可比较字符串与其逆序副本，但双指针只需 O(1) 额外空间。",
    ],
  }),
  defineProblem({
    ref: "ascend:foundation:char-frequency:v1",
    title: "字符出现次数",
    difficultyBand: "foundation",
    statementMarkdown: "给定一个只含小写字母的字符串和一个目标字符，统计目标字符出现次数。",
    inputSpecification: "第一行是非空字符串；第二行是一个小写字母。",
    outputSpecification: "输出目标字符的出现次数。",
    examples: [
      { input: "banana\na\n", output: "3\n" },
      { input: "xyz\nq\n", output: "0\n" },
    ],
    skills: ["string-scan", "counting", "character"],
    transferGroup: "string-scan",
    hints: [
      "目标字符可能一次也不出现。",
      "逐字符扫描并与目标字符比较。",
      "相等时计数器加一。",
      "时间复杂度 O(|s|)，不需要建立完整频次数组。",
    ],
  }),
  defineProblem({
    ref: "ascend:foundation:balanced-brackets:v1",
    title: "括号序列检查",
    difficultyBand: "standard",
    statementMarkdown: "判断由 `()[]{}` 组成的字符串是否为合法括号序列。",
    inputSpecification: "一行一个非空括号字符串，长度不超过 $2\\times10^5$。",
    outputSpecification: "合法输出 `YES`，否则输出 `NO`。",
    examples: [
      { input: "([]{})\n", output: "YES\n" },
      { input: "([)]\n", output: "NO\n" },
    ],
    skills: ["stack", "string-scan", "matching"],
    transferGroup: "stack-state",
    hints: [
      "右括号必须与最近一个尚未匹配的左括号配对。",
      "后进先出关系对应栈。",
      "左括号入栈；右括号检查栈顶，失败立即 NO；结束时栈必须为空。",
      "建立右括号到左括号的映射可减少重复条件。",
    ],
  }),
  defineProblem({
    ref: "ascend:foundation:run-length-encode:v1",
    title: "连续字符压缩",
    difficultyBand: "foundation",
    statementMarkdown: "把小写字母字符串的每段连续相同字符编码为“字符+段长度”。",
    inputSpecification: "一行一个非空小写字符串，长度不超过 $2\\times10^5$。",
    outputSpecification: "输出连续段编码，不插入空格。",
    examples: [
      { input: "aaabbc\n", output: "a3b2c1\n" },
      { input: "z\n", output: "z1\n" },
    ],
    skills: ["string-scan", "run-length", "state-machine"],
    transferGroup: "string-scan",
    hints: [
      "只合并相邻且相同的字符。",
      "维护当前字符和当前段长度。",
      "字符变化时输出旧段并重置；循环后别忘记输出最后一段。",
      "一次扫描即可，注意单字符和整串相同两种边界。",
    ],
  }),
  defineProblem({
    ref: "ascend:foundation:word-count:v1",
    title: "一行中的单词数",
    difficultyBand: "foundation",
    statementMarkdown: "统计一行文本中由一个或多个空格分隔的非空单词数量。",
    inputSpecification: "输入一行 ASCII 文本，长度不超过 $2\\times10^5$，可能为空或有前后空格。",
    outputSpecification: "输出单词数量。",
    examples: [
      { input: "  learn   algorithms well  \n", output: "3\n" },
      { input: "\n", output: "0\n" },
    ],
    skills: ["string-scan", "state-machine", "whitespace"],
    transferGroup: "string-scan",
    hints: [
      "多个连续空格只构成一个分隔区。",
      "只有从空格进入非空格时才开始一个新单词。",
      "维护 inWord；遇到非空格且 inWord 为假时计数并置真。",
      "也可按空白切分并过滤空串，但要确认语言函数对空行的行为。",
    ],
  }),
  defineProblem({
    ref: "ascend:standard:lower-bound:v1",
    title: "第一个不小于目标的位置",
    difficultyBand: "standard",
    statementMarkdown: "在非递减数组中找到第一个大于等于目标值 $x$ 的元素下标；不存在则输出 -1。",
    inputSpecification: "第一行是 $n$ 和 $x$；第二行是 $n$ 个非递减整数。下标从 0 开始。",
    outputSpecification: "输出目标下标或 -1。",
    examples: [
      { input: "5 4\n1 2 4 4 7\n", output: "2\n" },
      { input: "4 3\n1 2 5 9\n", output: "2\n" },
    ],
    skills: ["binary-search", "sorted-array", "boundary"],
    transferGroup: "ordered-search",
    hints: [
      "目标值不一定在数组中；要找的是第一个不小于它的位置。",
      "维护半开区间 [left,right)，根据 a[mid] >= x 收缩右边界。",
      "循环结束 left 是候选；若 left==n 则输出 -1。",
      "这就是 lower_bound 契约，重复值时必须返回最左位置。",
    ],
  }),
  defineProblem({
    ref: "ascend:foundation:merge-sorted:v1",
    title: "合并两个有序数组",
    difficultyBand: "foundation",
    statementMarkdown: "把两个非递减整数数组合并为一个非递减数组。",
    inputSpecification: "第一行是 $n,m$；随后两行分别包含两个数组，允许其中一个为空。",
    outputSpecification: "一行输出合并结果，空格分隔。",
    examples: [
      { input: "3 4\n1 4 9\n2 2 8 10\n", output: "1 2 2 4 8 9 10\n" },
      { input: "0 3\n\n1 2 3\n", output: "1 2 3\n" },
    ],
    skills: ["two-pointers", "merge", "sorted-array"],
    transferGroup: "two-pointers",
    hints: [
      "两个输入数组都已经有序。",
      "分别用一个指针指向尚未合并的最小元素。",
      "每次取两者较小值；一个数组耗尽后追加另一个剩余部分。",
      "时间复杂度 O(n+m)，不需要重新排序。",
    ],
  }),
  defineProblem({
    ref: "ascend:foundation:unique-sorted:v1",
    title: "有序数组去重",
    difficultyBand: "foundation",
    statementMarkdown: "给定一个非递减数组，只保留每个不同值的第一次出现并输出。",
    inputSpecification: "第一行是 $n$；第二行是 $n$ 个非递减整数，$1\\le n\\le2\\times10^5$。",
    outputSpecification: "一行输出去重后的值，空格分隔。",
    examples: [
      { input: "7\n1 1 2 2 2 5 5\n", output: "1 2 5\n" },
      { input: "3\n-1 0 1\n", output: "-1 0 1\n" },
    ],
    skills: ["sorted-array", "deduplication", "two-pointers"],
    transferGroup: "ordered-scan",
    hints: [
      "相同值在有序数组中一定连续出现。",
      "只需把当前值与上一个已输出值比较。",
      "输出第一个元素；从第二个开始，仅在 a[i]!=a[i-1] 时输出。",
      "可以流式输出，也可以先收集结果以便统一处理空格。",
    ],
  }),
  defineProblem({
    ref: "ascend:standard:two-sum-sorted:v1",
    title: "有序数组两数和",
    difficultyBand: "standard",
    statementMarkdown: "在严格递增数组中寻找两个不同位置，使其元素之和等于目标值；输出下标，不存在则输出 `-1 -1`。",
    inputSpecification: "第一行是 $n,target$；第二行是 $n$ 个严格递增整数。下标从 0 开始。",
    outputSpecification: "输出双指针算法首次找到的 `left right`，或 `-1 -1`。",
    examples: [
      { input: "5 9\n1 2 4 7 11\n", output: "1 3\n" },
      { input: "4 20\n1 3 6 10\n", output: "-1 -1\n" },
    ],
    skills: ["two-pointers", "sorted-array", "sum-invariant"],
    transferGroup: "two-pointers",
    hints: [
      "数组严格递增，因此两端和的变化方向可预测。",
      "和太小时移动左指针，和太大时移动右指针。",
      "left=0,right=n-1；循环到 left>=right 或找到目标。",
      "该方法是 O(n)，比枚举所有二元组更适合大输入。",
    ],
  }),
  defineProblem({
    ref: "ascend:foundation:rotate-right:v1",
    title: "数组循环右移",
    difficultyBand: "foundation",
    statementMarkdown: "把长度为 $n$ 的数组循环右移 $k$ 位。",
    inputSpecification: "第一行是 $n,k$；第二行是 $n$ 个整数，$1\\le n\\le2\\times10^5$。",
    outputSpecification: "输出右移后的数组。",
    examples: [
      { input: "5 2\n1 2 3 4 5\n", output: "4 5 1 2 3\n" },
      { input: "4 6\n1 2 3 4\n", output: "3 4 1 2\n" },
    ],
    skills: ["array", "modulo", "rotation", "indexing"],
    transferGroup: "array-transform",
    hints: [
      "当 k 大于 n 时，完整转一圈不改变数组。",
      "先令 k%=n；结果由末尾 k 个元素和前面 n-k 个元素组成。",
      "依次输出 a[n-k..n-1] 和 a[0..n-k-1]。",
      "也可使用三次反转完成原地旋转。",
    ],
  }),
  defineProblem({
    ref: "ascend:standard:prefix-range-query:v1",
    title: "多次区间求和",
    difficultyBand: "standard",
    statementMarkdown: "给定数组和多次查询，每次求闭区间 $[l,r]$ 的元素和。",
    inputSpecification: "第一行是 $n,q$；第二行是数组；随后 $q$ 行每行是 0-based 的 $l,r$。",
    outputSpecification: "每个查询输出一行区间和。",
    examples: [
      { input: "5 3\n2 -1 4 3 6\n0 2\n1 3\n4 4\n", output: "5\n6\n6\n" },
      { input: "3 1\n10 20 30\n0 2\n", output: "60\n" },
    ],
    skills: ["prefix-sum", "range-query", "integer-overflow"],
    transferGroup: "integer-aggregation",
    hints: [
      "逐次扫描区间在查询很多时会太慢。",
      "构造 prefix[i+1] 表示前 i+1 个元素的和。",
      "区间和等于 prefix[r+1]-prefix[l]。",
      "预处理 O(n)，每次查询 O(1)；使用 64 位整数。",
    ],
  }),
  defineProblem({
    ref: "ascend:standard:max-subarray:v1",
    title: "最大连续子段和",
    difficultyBand: "standard",
    statementMarkdown: "求非空整数数组的最大连续子段和。",
    inputSpecification: "第一行是 $n$；第二行是 $n$ 个整数，$1\\le n\\le2\\times10^5$。",
    outputSpecification: "输出最大连续子段和。",
    examples: [
      { input: "8\n-2 1 -3 4 -1 2 1 -5\n", output: "6\n" },
      { input: "3\n-5 -2 -8\n", output: "-2\n" },
    ],
    skills: ["dynamic-programming", "array-scan", "kadane", "invariant"],
    transferGroup: "one-dimensional-dp",
    hints: [
      "答案要求非空，因此全负数组不能返回 0。",
      "维护“必须以当前位置结尾的最大子段和”。",
      "current=max(a[i],current+a[i])，answer=max(answer,current)。",
      "这是 Kadane 算法，时间 O(n)、额外空间 O(1)。",
    ],
  }),
  defineProblem({
    ref: "ascend:standard:interval-merge-count:v1",
    title: "合并区间后的段数",
    difficultyBand: "standard",
    statementMarkdown: "给定若干闭区间，合并所有相交或端点接触的区间，输出剩余区间数量。",
    inputSpecification: "第一行是 $n$；随后 $n$ 行是 $l,r$，满足 $l\\le r$。",
    outputSpecification: "输出合并后的区间数量。",
    examples: [
      { input: "4\n1 3\n2 5\n8 10\n10 12\n", output: "2\n" },
      { input: "3\n-5 -4\n0 1\n7 9\n", output: "3\n" },
    ],
    skills: ["sorting", "interval", "greedy", "scan"],
    transferGroup: "sort-and-scan",
    hints: [
      "输入区间不保证有序。",
      "先按左端点排序，再维护当前合并区间的右端点。",
      "若 next.left<=currentRight 就扩展，否则答案加一并开始新区间。",
      "排序 O(n log n)，扫描 O(n)。闭区间端点相等时应合并。",
    ],
  }),
  defineProblem({
    ref: "ascend:standard:grid-shortest-path:v1",
    title: "网格最短路",
    difficultyBand: "standard",
    statementMarkdown: "在含障碍的网格中，从 `S` 出发每步上下左右移动一格，求到 `T` 的最少步数。",
    inputSpecification: "第一行是 $n,m$；随后是由 `. # S T` 构成的网格，恰有一个 S 和 T。",
    outputSpecification: "可达时输出最少步数，否则输出 -1。",
    examples: [
      { input: "3 4\nS..#\n.#..\n...T\n", output: "5\n" },
      { input: "2 3\nS#T\n###\n", output: "-1\n" },
    ],
    skills: ["breadth-first-search", "grid", "queue", "shortest-path"],
    transferGroup: "graph-traversal",
    hints: [
      "每条移动边代价都相同。",
      "无权图的最短步数使用 BFS，并在首次访问时记录距离。",
      "把 S 入队；每次扩展四邻格，跳过越界、障碍和已访问位置。",
      "首次到达 T 的距离就是答案；队列耗尽仍未到达则为 -1。",
    ],
  }),
  defineProblem({
    ref: "ascend:standard:gcd-lcm:v1",
    title: "最大公约数与最小公倍数",
    difficultyBand: "standard",
    statementMarkdown: "给定两个非负整数（不同时为 0），输出最大公约数和最小公倍数。",
    inputSpecification: "一行包含 $a,b$，$0\\le a,b\\le10^9$，且不同时为 0。",
    outputSpecification: "输出 `gcd lcm`。",
    examples: [
      { input: "12 18\n", output: "6 36\n" },
      { input: "0 7\n", output: "7 0\n" },
    ],
    skills: ["euclidean-algorithm", "divisibility", "integer-overflow"],
    transferGroup: "number-theory",
    hints: [
      "一个数为 0 时，最大公约数是另一个数，最小公倍数是 0。",
      "使用欧几里得算法反复替换 (a,b) 为 (b,a%b)。",
      "先保存原值；gcd 求出后用 a/gcd*b 计算 lcm。",
      "先做除法再乘法可降低溢出风险，C++ 使用 long long。",
    ],
  }),
  defineProblem({
    ref: "ascend:standard:coin-change-min:v1",
    title: "最少硬币数",
    difficultyBand: "standard",
    statementMarkdown: "给定若干种正整数面额，每种可使用无限次，求组成目标金额所需的最少硬币数。",
    inputSpecification: "第一行是 $n,amount$；第二行是 $n$ 个正整数面额，$amount\\le10^5$。",
    outputSpecification: "可组成时输出最少数量，否则输出 -1。",
    examples: [
      { input: "3 11\n1 5 7\n", output: "3\n" },
      { input: "2 3\n2 4\n", output: "-1\n" },
    ],
    skills: ["dynamic-programming", "unbounded-knapsack", "minimum"],
    transferGroup: "knapsack-dp",
    hints: [
      "贪心选择最大面额对任意面额集合不一定正确。",
      "令 dp[x] 表示组成金额 x 的最少硬币数。",
      "dp[0]=0；对每个 x 和 coin，若 x>=coin 就尝试 dp[x-coin]+1。",
      "不可达状态设为大值，最终仍为大值时输出 -1。",
    ],
  }),
  defineProblem({
    ref: "ascend:standard:lis-length:v1",
    title: "最长严格递增子序列长度",
    difficultyBand: "standard",
    statementMarkdown: "求整数数组的最长严格递增子序列长度；子序列不要求连续。",
    inputSpecification: "第一行是 $n$；第二行是 $n$ 个整数，$1\\le n\\le2\\times10^5$。",
    outputSpecification: "输出最长严格递增子序列长度。",
    examples: [
      { input: "8\n10 9 2 5 3 7 101 18\n", output: "4\n" },
      { input: "4\n2 2 2 2\n", output: "1\n" },
    ],
    skills: ["binary-search", "dynamic-programming", "subsequence"],
    transferGroup: "ordered-search",
    hints: [
      "子序列可以跳过元素，但必须保持原相对顺序；严格递增不接受相等。",
      "维护 tails[len-1]：长度为 len 的递增子序列可能的最小结尾。",
      "对每个 x，在 tails 中 lower_bound 第一个 >=x 的位置并替换或追加。",
      "tails 的长度是答案，整体复杂度 O(n log n)。",
    ],
  }),
  defineProblem({
    ref: "ascend:standard:knapsack-01:v1",
    title: "零一背包最大价值",
    difficultyBand: "standard",
    statementMarkdown: "每件物品最多选一次，在总重量不超过容量时求最大总价值。",
    inputSpecification: "第一行是 $n,C$；第二行是重量；第三行是价值，$n\\le200,C\\le10^4$。",
    outputSpecification: "输出可获得的最大总价值。",
    examples: [
      { input: "3 5\n2 3 4\n3 4 5\n", output: "7\n" },
      { input: "2 0\n1 2\n10 20\n", output: "0\n" },
    ],
    skills: ["dynamic-programming", "zero-one-knapsack", "space-optimization"],
    transferGroup: "knapsack-dp",
    hints: [
      "每件物品只能使用一次。",
      "令 dp[c] 表示容量不超过 c 的最大价值。",
      "逐件处理物品，并让容量 c 从 C 倒序到 weight。",
      "倒序是关键：正序会在同一轮重复使用当前物品。",
    ],
  }),
  defineProblem({
    ref: "ascend:standard:connected-components:v1",
    title: "无向图连通分量",
    difficultyBand: "standard",
    statementMarkdown: "给定一个无向图，求它的连通分量数量。",
    inputSpecification: "第一行是 $n,m$；随后 $m$ 行是 1-based 顶点 $u,v$，无自环。",
    outputSpecification: "输出连通分量数量。",
    examples: [
      { input: "5 3\n1 2\n2 3\n4 5\n", output: "2\n" },
      { input: "4 0\n", output: "4\n" },
    ],
    skills: ["depth-first-search", "breadth-first-search", "graph", "connectivity"],
    transferGroup: "graph-traversal",
    hints: [
      "孤立顶点自身也是一个连通分量。",
      "从每个尚未访问的顶点启动一次 DFS 或 BFS。",
      "每次新启动遍历时答案加一，并标记能到达的全部顶点。",
      "邻接表使总复杂度为 O(n+m)。",
    ],
  }),
] as const;
