export type PlannerAcceptanceFixture = {
  id: string;
  phase: 1 | 2 | 3 | 4 | 5 | 6;
  title: string;
  given: string;
  when: string;
  then: string[];
};

export const plannerAcceptanceFixtures: PlannerAcceptanceFixture[] = [
  {
    id: "capture-inbox-idempotent",
    phase: 2,
    title: "十秒收集到 Inbox",
    given: "用户位于任意 Planner 页面",
    when: "使用同一 clientMutationId 连续提交一条任务",
    then: ["Inbox 只出现一条任务", "返回稳定 UUID 与 version"],
  },
  {
    id: "due-and-schedule-independent",
    phase: 2,
    title: "到期与排期独立",
    given: "任务明天 18:00 到期",
    when: "任务被拖入今天 09:00 的日历",
    then: ["due_at 保持原值", "scheduled_start_at 与 scheduled_end_at 更新"],
  },
  {
    id: "today-combined-sources",
    phase: 2,
    title: "Today 组合来源",
    given: "一条任务今天到期，另一条任务今天排期",
    when: "打开 Today",
    then: ["两条任务均显示", "来源标记清晰"],
  },
  {
    id: "subtask-depth",
    phase: 2,
    title: "子任务三层上限",
    given: "任务已经位于深度 3",
    when: "继续创建子任务",
    then: ["写入被拒绝", "现有层级保持完整"],
  },
  {
    id: "trash-restore",
    phase: 2,
    title: "回收站恢复",
    given: "任务已软删除",
    when: "用户从 Trash 恢复",
    then: ["deleted_at 清空", "任务回到原清单与稳定排序位置"],
  },
  {
    id: "workspace-isolation",
    phase: 2,
    title: "两个 workspace 隔离",
    given: "A 与 B workspace 各有同名任务",
    when: "A 查询、更新和删除任务",
    then: ["结果仅包含 A 数据", "B 的 version 与内容保持原值"],
  },
  {
    id: "timed-event",
    phase: 3,
    title: "定时事件",
    given: "Asia/Shanghai 的 09:00–10:30 事件",
    when: "月、周、日和议程视图加载同一范围",
    then: ["四个视图引用同一事件 UUID", "UTC 瞬时值一致"],
  },
  {
    id: "all-day-exclusive-end",
    phase: 3,
    title: "全天多日 exclusive end",
    given: "8 月 1 日至 8 月 3 日的全天事件",
    when: "保存并投影到 FullCalendar",
    then: ["start_date 为 8 月 1 日", "end_date_exclusive 为 8 月 4 日"],
  },
  {
    id: "cross-midnight-event",
    phase: 3,
    title: "跨午夜事件",
    given: "23:30–次日 01:00 的定时事件",
    when: "查询覆盖两日的日历范围",
    then: ["事件仅返回一次", "两日议程均可定位该事件"],
  },
  {
    id: "task-unschedule",
    phase: 3,
    title: "任务移回待排区",
    given: "任务已有计划时间与到期时间",
    when: "从时间轴拖回待排区",
    then: ["计划字段清空", "到期字段保持原值"],
  },
  {
    id: "recurrence-dst",
    phase: 4,
    title: "DST 后本地时钟稳定",
    given: "America/New_York 每天 09:00 的重复事件",
    when: "实例跨越春季 DST",
    then: ["每个实例本地时间保持 09:00", "UTC 偏移按 DST 改变"],
  },
  {
    id: "recurrence-month-end",
    phase: 4,
    title: "月末重复",
    given: "每月 31 日重复",
    when: "展开一年实例",
    then: ["仅生成存在 31 日的月份", "occurrence_key 全部唯一"],
  },
  {
    id: "recurrence-exception",
    phase: 4,
    title: "单次重复例外",
    given: "每周重复事件已有四个实例",
    when: "第二个实例改期",
    then: ["主 RRULE 保持", "原实例被例外覆盖", "其他实例保持原值"],
  },
  {
    id: "after-completion-task",
    phase: 4,
    title: "完成后重复任务",
    given: "完成后 3 天生成下一次的任务",
    when: "完成当前实例并重试同一 operation id",
    then: ["下一实例从完成时刻计算", "下一实例仅生成一条"],
  },
  {
    id: "reminder-worker-restart",
    phase: 4,
    title: "提醒 Worker 重启",
    given: "Worker 领取提醒后进程退出",
    when: "lease 到期后新 Worker 扫描",
    then: ["提醒重新进入领取", "已确认 sent 的提醒保持单次发送"],
  },
  {
    id: "planner-search",
    phase: 5,
    title: "跨任务与事件搜索",
    given: "任务和事件均包含关键词与标签",
    when: "使用 type、tag 与日期过滤语法搜索",
    then: ["结果满足 workspace 与过滤条件", "每条结果提供实体跳转"],
  },
  {
    id: "offline-create-reconnect",
    phase: 5,
    title: "离线创建后重连",
    given: "设备拥有当前 workspace 快照",
    when: "离线创建任务并恢复网络",
    then: ["outbox 保留稳定 operation id", "服务端与本地最终各有一条任务"],
  },
  {
    id: "two-device-conflict",
    phase: 5,
    title: "两设备版本冲突",
    given: "两台设备读取同一任务 version",
    when: "两台设备先后提交不同标题",
    then: ["后提交返回 conflict 与 latest", "冲突面板可选择刷新或覆盖"],
  },
  {
    id: "schedule-suggestion",
    phase: 5,
    title: "确定性排期建议",
    given: "任务时长、到期、工作时间和 busy 事件均已知",
    when: "请求三个候选空档",
    then: ["候选位于到期前可用时段", "每个候选包含评分解释"],
  },
  {
    id: "responsive-keyboard",
    phase: 6,
    title: "响应式与键盘闭环",
    given: "桌面、平板与 390px 手机视口",
    when: "仅用键盘创建、编辑、排期、搜索、完成并关闭编辑器",
    then: ["页面无横向溢出", "焦点可见且归还正确", "触控目标至少 44px"],
  },
];
