import type { CalendarEvent, PlannerTask, TaskList } from "@/lib/planner/types";
import type { SubjectOverview } from "@/lib/repo/knowledge";
import type { ExamCountdown } from "@/lib/repo/settings";
import type { HomeSnapshot, LearningAnalytics, WeeklyCapacity } from "@/lib/repo/stats";

const now = "2026-08-01T08:00:00.000Z";
const task = (input: Partial<PlannerTask> & Pick<PlannerTask, "id" | "title">): PlannerTask => {
  const { id, title, ...overrides } = input;
  return {
    id,
    workspace_id: "mock-workspace",
    list_id: "list-today",
    parent_task_id: null,
    depth: 0,
    title,
    notes: "",
    subject_code: null,
    status: "open",
    priority: 2,
    due_date: "2026-08-01",
    due_at: null,
    due_timezone: "Asia/Shanghai",
    scheduled_start_at: null,
    scheduled_end_at: null,
    scheduled_timezone: "Asia/Shanghai",
    scheduled_all_day: 0,
    estimated_minutes: 45,
    series_id: null,
    occurrence_key: null,
    sort_order: 0,
    deleted_at: null,
    completed_at: null,
    canceled_at: null,
    version: 1,
    legacy_day_task_id: null,
    created_at: now,
    updated_at: now,
    ...overrides,
  };
};
const event = (input: Partial<CalendarEvent> & Pick<CalendarEvent, "id" | "title">): CalendarEvent => {
  const { id, title, ...overrides } = input;
  return {
    id,
    workspace_id: "mock-workspace",
    calendar_id: "calendar-study",
    title,
    description: "",
    location: "",
    url: "",
    subject_code: null,
    kind: "focus",
    busy_status: "busy",
    start_at: null,
    end_at: null,
    timezone: "Asia/Shanghai",
    start_date: null,
    end_date_exclusive: null,
    all_day: 0,
    recurrence_rule: null,
    recurrence_until: null,
    recurring_event_id: null,
    original_start_at: null,
    exception_kind: null,
    migration_key: null,
    deleted_at: null,
    version: 1,
    created_at: now,
    updated_at: now,
    ...overrides,
  };
};
export const lists = [
  {
    id: "list-today",
    workspace_id: "mock-workspace",
    name: "今日推进",
    color_token: "coral",
    icon: "target",
    sort_order: 0,
    is_inbox: 1,
    archived_at: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "list-retest",
    workspace_id: "mock-workspace",
    name: "复测队列",
    color_token: "mint",
    icon: "repeat",
    sort_order: 1,
    is_inbox: 0,
    archived_at: null,
    created_at: now,
    updated_at: now,
  },
] satisfies TaskList[];
export const tasks = [
  task({
    id: "task-proof",
    title: "闭卷复述：TCP 拥塞控制",
    subject_code: "CS408",
    priority: 1,
    estimated_minutes: 35,
    scheduled_start_at: "2026-08-01T01:00:00.000Z",
    scheduled_end_at: "2026-08-01T01:35:00.000Z",
  }),
  task({
    id: "task-tree",
    title: "二叉树变式题 3 道",
    subject_code: "ALGO",
    estimated_minutes: 55,
    scheduled_start_at: "2026-08-01T02:00:00.000Z",
    scheduled_end_at: "2026-08-01T02:55:00.000Z",
  }),
  task({
    id: "task-review",
    title: "重做错题：页式存储地址转换",
    subject_code: "OS",
    priority: 1,
    estimated_minutes: 25,
    list_id: "list-retest",
  }),
  task({ id: "task-notes", title: "整理本周模考失分归因", subject_code: "MATH", priority: 3, estimated_minutes: 30 }),
] satisfies PlannerTask[];
export const events = [
  event({
    id: "event-class",
    title: "计算机网络专题课",
    subject_code: "CS408",
    kind: "class",
    start_at: "2026-08-01T05:00:00.000Z",
    end_at: "2026-08-01T06:30:00.000Z",
  }),
  event({
    id: "event-mock",
    title: "周模考",
    subject_code: "MATH",
    kind: "exam",
    start_at: "2026-08-02T01:00:00.000Z",
    end_at: "2026-08-02T03:30:00.000Z",
  }),
  event({
    id: "event-deadline",
    title: "报名材料截止",
    kind: "milestone",
    all_day: 1,
    start_date: "2026-08-05",
    end_date_exclusive: "2026-08-06",
    timezone: null,
  }),
] satisfies CalendarEvent[];
export const home = {
  today: { assets: 3, studyMinutes: 92, reviews: 6, mistakes: 2, mockExams: 0 },
  dueReviews: 8,
  dueMistakes: 3,
  openTasks: 4,
  doneTasks: 2,
  streak: 12,
} satisfies HomeSnapshot;
export const capacity = {
  start: "2026-07-27",
  end: "2026-08-02",
  targetMinutes: 900,
  studiedMinutes: 420,
  plannedMinutes: 315,
  overdueOpenMinutes: 45,
  remainingToTarget: 480,
  unallocatedMinutes: 165,
  overloadMinutes: 0,
  completionPercent: 47,
  days: [65, 80, 42, 96, 45, 92, 0].map((studiedMinutes, index) => ({
    day: `2026-${index < 5 ? "07" : "08"}-${[27, 28, 29, 30, 31, 1, 2][index].toString().padStart(2, "0")}`,
    studiedMinutes,
    plannedMinutes: index === 5 ? 180 : index === 6 ? 135 : 0,
    suggestedMinutes: index === 5 ? 60 : index === 6 ? 105 : 0,
  })),
} satisfies WeeklyCapacity;
export const analytics = {
  dailyMinutes: capacity.days.map(({ day, studiedMinutes }) => ({ day, minutes: studiedMinutes })),
  scoreDist: [1, 2, 5, 4] as [number, number, number, number],
  weakPoints: [
    {
      id: "weak-1",
      subjectCode: "CS408",
      title: "TCP 拥塞窗口",
      tierName: "易错",
      mastery: 38,
      nextReview: "2026-08-01",
      openMistakes: 2,
      recentFailures: 2,
      priorityScore: 136,
      reasons: ["连续两次回忆失败", "存在未毕业错题"],
    },
    {
      id: "weak-2",
      subjectCode: "MATH",
      title: "多元函数极值",
      tierName: "不稳",
      mastery: 52,
      nextReview: "2026-08-01",
      openMistakes: 1,
      recentFailures: 1,
      priorityScore: 98,
      reasons: ["信心高于结果"],
    },
  ],
} satisfies Pick<LearningAnalytics, "dailyMinutes" | "scoreDist" | "weakPoints">;
export const subjects = [
  {
    code: "CS408",
    name: "计算机综合",
    description: "数据结构、计组、操作系统、网络",
    track: "written",
    pointCount: 126,
    masteredCount: 78,
    dueCount: 8,
    assetCount: 31,
    openMistakes: 6,
    avgMastery: 66,
  },
  {
    code: "MATH",
    name: "高等数学",
    description: "极限、微积分与线性代数",
    track: "written",
    pointCount: 94,
    masteredCount: 61,
    dueCount: 4,
    assetCount: 18,
    openMistakes: 3,
    avgMastery: 71,
  },
] satisfies SubjectOverview[];
export const exams = [{ name: "秋季统考", date: "2026-12-20", targetScore: 380 }] satisfies ExamCountdown[];
