import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import process from "node:process";
import { operationManifest } from "../src/lib/agent/operations";

const target = path.resolve("docs/generated/agent-operations.md");
const rendered = render();

if (process.argv.includes("--check")) {
  const current = readFileSync(target, "utf8");
  if (current !== rendered) {
    process.stderr.write("Agent operation catalog is stale; run npm run docs:agent-operations\n");
    process.exitCode = 1;
  } else {
    process.stdout.write(`Agent operation catalog is current (${operationManifest().length} operations)\n`);
  }
} else {
  writeFileSync(target, rendered);
  process.stdout.write(`Generated ${path.relative(process.cwd(), target)} (${operationManifest().length} operations)\n`);
}

function render(): string {
  const rows = operationManifest().map((operation) => {
    const kind = operation.readOnly ? "读" : operation.destructive ? "破坏性写入" : "写入";
    const tool = operation.id.replace(/[.-]/g, "_");
    return `| \`${operation.id}\` | \`${tool}\` | ${kind} | ${escapeCell(operation.description)} |`;
  });
  return [
    "<!-- Generated by scripts/generate-agent-operation-docs.ts. -->",
    "# Ascend Agent 操作清单",
    "",
    `当前共 ${rows.length} 个操作。数据源为 [\`operationManifest()\`](../../src/lib/agent/operations.ts)。`,
    "",
    "MCP 工具名由 CLI operation 的点号和连字符替换为下划线。运行 `npm run ascend -- tools` 可读取 JSON 清单。",
    "",
    "| CLI operation | MCP tool | 类型 | 说明 |",
    "| --- | --- | --- | --- |",
    ...rows,
    "",
  ].join("\n");
}

function escapeCell(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", " ");
}
